FROM node:lts-alpine

WORKDIR /usr/src/server

ENV TINI_VERSION=v0.16.1

RUN apk add --no-cache tini
ENTRYPOINT ["/sbin/tini", "--"]

COPY package*.json ./

RUN npm ci
RUN npm i -g pino-pretty
COPY . .

EXPOSE ${PORT}

USER node
CMD [ "npm", "run", "start:dev", "|", "pino-pretty", "-t", "-c" ]
