name: build & test
on:
  push:
    paths-ignore:
      - ".github/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.17.2
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: echo '${{ secrets.DOT_ENV }}' > .env
      - run: npm run test
